"""empty message

Revision ID: e4cf023912e4
Revises: 82184d7d1e88
Create Date: 2018-11-05 00:19:13.073597

"""

# revision identifiers, used by Alembic.
revision = 'e4cf023912e4'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('account_number_code', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('bank_id', sa.String(length=100), nullable=True),
    sa.Column('bank_id_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_account'))
    )
    op.create_index(op.f('ix_bank_account_account_name'), 'bank_account', ['account_name'], unique=False)
    op.create_index(op.f('ix_bank_account_account_number'), 'bank_account', ['account_number'], unique=False)
    op.create_index(op.f('ix_bank_account_account_number_code'), 'bank_account', ['account_number_code'], unique=False)
    op.create_index(op.f('ix_bank_account_address'), 'bank_account', ['address'], unique=False)
    op.create_index(op.f('ix_bank_account_bank_id'), 'bank_account', ['bank_id'], unique=False)
    op.create_index(op.f('ix_bank_account_bank_id_code'), 'bank_account', ['bank_id_code'], unique=False)
    op.create_index(op.f('ix_bank_account_name'), 'bank_account', ['name'], unique=False)
    op.create_table('charges_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bearer_code', sa.String(), nullable=True),
    sa.Column('receiver_charges_amount', sa.DECIMAL(), nullable=True),
    sa.Column('receiver_charges_currency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charges_information'))
    )
    op.create_table('fx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_reference', sa.String(), nullable=True),
    sa.Column('exchange_rate', sa.DECIMAL(), nullable=True),
    sa.Column('original_amount', sa.DECIMAL(), nullable=True),
    sa.Column('original_currency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fx'))
    )
    op.create_table('payment',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('organisation_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    op.create_index(op.f('ix_payment_organisation_id'), 'payment', ['organisation_id'], unique=False)
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['charges_information.id'], name=op.f('fk_charge_parent_id_charges_information')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charge'))
    )
    op.create_table('payment_attributes',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('beneficiary_party_id', sa.Integer(), nullable=True),
    sa.Column('charges_information_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('debtor_party_id', sa.Integer(), nullable=True),
    sa.Column('end_to_end_reference', sa.String(), nullable=True),
    sa.Column('fx_id', sa.Integer(), nullable=True),
    sa.Column('numeric_reference', sa.String(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('payment_purpose', sa.String(), nullable=True),
    sa.Column('payment_scheme', sa.String(), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('processing_date', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('scheme_payment_sub_type', sa.String(), nullable=True),
    sa.Column('scheme_payment_type', sa.String(), nullable=True),
    sa.Column('sponsor_party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_party_id'], ['bank_account.id'], name=op.f('fk_payment_attributes_beneficiary_party_id_bank_account')),
    sa.ForeignKeyConstraint(['charges_information_id'], ['charges_information.id'], name=op.f('fk_payment_attributes_charges_information_id_charges_information')),
    sa.ForeignKeyConstraint(['debtor_party_id'], ['bank_account.id'], name=op.f('fk_payment_attributes_debtor_party_id_bank_account')),
    sa.ForeignKeyConstraint(['fx_id'], ['fx.id'], name=op.f('fk_payment_attributes_fx_id_fx')),
    sa.ForeignKeyConstraint(['id'], ['payment.id'], name=op.f('fk_payment_attributes_id_payment')),
    sa.ForeignKeyConstraint(['sponsor_party_id'], ['bank_account.id'], name=op.f('fk_payment_attributes_sponsor_party_id_bank_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_attributes'))
    )
    op.create_index(op.f('ix_payment_attributes_beneficiary_party_id'), 'payment_attributes', ['beneficiary_party_id'], unique=False)
    op.create_index(op.f('ix_payment_attributes_debtor_party_id'), 'payment_attributes', ['debtor_party_id'], unique=False)
    op.create_index(op.f('ix_payment_attributes_fx_id'), 'payment_attributes', ['fx_id'], unique=False)
    op.create_index(op.f('ix_payment_attributes_sponsor_party_id'), 'payment_attributes', ['sponsor_party_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_attributes_sponsor_party_id'), table_name='payment_attributes')
    op.drop_index(op.f('ix_payment_attributes_fx_id'), table_name='payment_attributes')
    op.drop_index(op.f('ix_payment_attributes_debtor_party_id'), table_name='payment_attributes')
    op.drop_index(op.f('ix_payment_attributes_beneficiary_party_id'), table_name='payment_attributes')
    op.drop_table('payment_attributes')
    op.drop_table('charge')
    op.drop_index(op.f('ix_payment_organisation_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_table('fx')
    op.drop_table('charges_information')
    op.drop_index(op.f('ix_bank_account_name'), table_name='bank_account')
    op.drop_index(op.f('ix_bank_account_bank_id_code'), table_name='bank_account')
    op.drop_index(op.f('ix_bank_account_bank_id'), table_name='bank_account')
    op.drop_index(op.f('ix_bank_account_address'), table_name='bank_account')
    op.drop_index(op.f('ix_bank_account_account_number_code'), table_name='bank_account')
    op.drop_index(op.f('ix_bank_account_account_number'), table_name='bank_account')
    op.drop_index(op.f('ix_bank_account_account_name'), table_name='bank_account')
    op.drop_table('bank_account')
    # ### end Alembic commands ###
